version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto11 # Specify the Java runtime version
    commands:
      - echo Installing Maven...
      - apt-get update
      - apt-get install -y maven
 
  pre_build:
    commands:
      - echo Checking out source code...
      - mvn --version # Validate Maven installation
 
  build:
    commands:
      - echo Building the application...
      - mvn clean # Compile and package the application
      - mvn compile
      - mvn test-compile
      - mvn test
      - mvn package
      - mvn install
      - mvn deploy
 
 
  post_build:
    commands:
      - echo Build completed successfully!
 
artifacts:
  files:
     - '**/*'   
cache:
  paths:
    - "/root/.m2/**/*" # Cache Maven dependencies for faster builds
