version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Building the application...
      - mvn clean package
artifacts:
  files:
    - target/*.jar
