version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven
      - curl -sL https://apache.org/dyn/closer.cgi/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.zip -o apache-maven-3.8.5-bin.zip
      - ls -l apache-maven-3.8.5-bin.zip
      - unzip -l apache-maven-3.8.5-bin.zip
      - unzip -o apache-maven-3.8.5-bin.zip -d /usr/local
      - export M2_HOME=/usr/local/apache-maven-3.8.5
      - export PATH=$M2_HOME/bin:$PATH
      - mvn --version  # Verify Maven installation
  build:
    commands:
      - echo Building the project
      - mvn clean package
artifacts:
  files:
    - target/*.jar
