version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - yum install -y maven  # Ensure Maven is installed
  build:
    commands:
      - echo Building the project...
      - mvn clean package  # Build the project and package it into JAR files
      - ls -l target  # List the contents of the target directory for debugging
