version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update -y
      - sudo apt-get install -y openjdk-11-jdk maven
      - java -version
      - mvn --version

  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean

  build:
    commands:
      - echo Building the project...
      - mvn package -e

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
  base-directory: 'target'
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'
